stages:
    - build
    - update_repo
    - deploy

build_jod:
    stage: build
    script:
    - pwd
    - cd ..
    - /bin/tar -zvcf nac-agent.tar.gz --exclude=nac-agent/.git/ nac-agent
    - /bin/rm -f /root/rpmbuild/RPMS/x86_64/*
    - /usr/bin/rpmbuild -ta nac-agent.tar.gz

update_repo_job:
    stage: update_repo
    script:
    - rsync -avrP /root/rpmbuild/RPMS/x86_64/* 192.168.10.64:/data/server/yum/other/6/x86_64/
    - ssh 192.168.10.64 createrepo /data/server/yum/other/6/x86_64/

deploy_job:
    stage: deploy
    script:
    - pwd